baseURL = '/'
languageCode = 'en-us'
title = 'Hugo - Blog'
defaultContentLanguage = "en"
enableRobotsTXT = true
paginate = 10

[params]
  author = "Hugo"
  description = "Hi! im Hugo and this is my blog"

[permalinks]
  posts = "/:filename/"
  
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON", "RSS", "Algolia"]

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'en'
    weight = 1
  [languages.es]
    contentDir = 'content/es'
    languageName = 'es'
    weight = 2

[markup]
  [markup.highlight]
    style = 'onedark'
    guessSyntax = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "permalink"]
params = ["tags"]