baseURL = 'https://deploy-preview-1--wadev-blog.netlify.app'
languageCode = 'en-us'
defaultContentLanguage = "EN"
title = 'Wadev - Blog'
defaultContentLanguageInSubdir = true

[params]
  author = "Wadev"
  description = "Hi! im Wadev and this is my blog"
  
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON", "RSS"]

[languages]
  [languages.en]
    baseURL = 'https://deploy-preview-1--wadev-blog.netlify.app/'
    contentDir = 'content'
    languageName = 'EN'
  [languages.es]
    contentDir = 'content/es'
    languageName = 'ES'
    baseURL = "https://deploy-preview-1--wadev-blog.netlify.app/es/"