baseURL = 'https://deploy-preview-1--wadev-blog.netlify.app'
languageCode = 'en-us'
title = 'Wadev - Blog'
defaultContentLanguageInSubdir = true

[params]
  author = "Wadev"
  description = "Hi! im Wadev and this is my blog"
  
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON", "RSS"]

[languages]
  [languages.en]
    contentDir = 'content'
    languageName = 'en'
    [languages.en.params]
      linkedin = 'https://deploy-preview-1--wadev-blog.netlify.app'
  [languages.es]
    contentDir = 'content/es'
    languageName = 'es'
    [languages.es.params]
      linkedin = 'https://deploy-preview-1--wadev-blog.netlify.app/es'