baseURL = '/'
languageCode = 'en-us'
efaultContentLanguage = "en"
title = 'Wadev - Blog'

[params]
  author = "Wadev"
  description = "Hi! im Wadev and this is my blog"
  
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON", "RSS"]

[languages]
  [languages.en]
    baseURL = ''
    contentDir = 'content'
    languageName = 'EN'
  [languages.es]
    baseURL = '/es'
    contentDir = 'content/es'
    languageName = 'ES'