baseURL = 'https://wadev-blog.netlify.app/'
languageCode = 'en-us'
efaultContentLanguage = "en"
title = 'Wadev - Blog'

[permalinks]
  posts = "/:filename/"

[params]
  author = "Wadev"
  description = "Hi! im Wadev and this is my blog"
  
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = [ "HTML", "JSON", "RSS"]