name: "Update Algolia Index"

on:
  push:
    branches:
      - 'main'
jobs:
  update-index:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build the site
        run: pnpm build

      - name: run update script
        run: pnpm algolia:update
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
  